name: fourgrant
favicon: null
layout_spectrum: 0.20618737558834255
typography_spectrum: 0.6663706307299435
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.795134145533666
  lightness: 0.3891606191173196
  saturation: 0.8405291314702481
  rhythmicContrast: 0.16132628615014255
purpose: []
